# Standalone with FMA Launcher example Scenario for LLM-D Deployment
#
# This scenario deploys Standalone mode with FMA Launcher
#
# IMPORTANT NOTE:
# All parameters not defined here will use the default values from defaults.yaml.
# Many commonly defined values were left blank (default) so that this scenario
# is applicable to as many environments as possible.
#
# The model parameter is left commented -- uncomment the model you want to deploy.
# Uncommenting a model here will override the default model from defaults.yaml.

scenario:
  - name: "launcher-example"
    common:
      model:
        name: meta-llama/Llama-3.1-8B-Instruct
        shortName: llama-3.1-8b
        path: models/meta-llama/Llama-3.1-8B-Instruct
        huggingfaceId: meta-llama/Llama-3.1-8B-Instruct

      images:
        benchmark:
          repository: ghcr.io/llm-d/llm-d-benchmark
          tag: nightly

      vllmCommon:
        # Shell used in the vLLM container `command:` field. Defaults to /bin/bash.
        # shell: /bin/sh
        flags:
          enforceEager: false
        volumes:
          - name: preprocesses
            type: configMap
            configMap:
              name: llm-d-benchmark-preprocesses
              defaultMode: 320
        volumeMounts:
          - name: preprocesses
            mountPath: /setup/preprocess

    modelservice:
      enabled: false

    fma:
      enabled: false

    standalone:
      enabled: true
      image:
        repository: ghcr.io/llm-d-incubation/llm-d-fast-model-actuation/launcher
        tag: v0.6.3
      vllm:
        customPreprocessCommand: "source /setup/preprocess/standalone-preprocess.sh ; /setup/preprocess/standalone-preprocess.py"
        loggingLevel: DEBUG
        additionalFlags:
          - "--enable-sleep-mode"
      launcher:
        enabled: true
        image:
          repository: ghcr.io/llm-d-incubation/llm-d-fast-model-actuation/launcher
          tag: v0.6.3
        customPreprocessCommand: "source /setup/preprocess/standalone-preprocess.sh ; /setup/preprocess/standalone-preprocess.py"

    harness:
      name: nop
      profile: nop.yaml
      executable: llm-d-benchmark.py
      experimentProfile: nop.yaml
      condaEnvName: nop-env
      waitTimeout: 3600
      loadParallelism: 1
      podLabel: llmdbench-harness-fma
      debug: false
      resources:
        cpu: 16
        memory: 32Gi
      output: local
      inferencePerf:
        rayonNumThreads: 4

    workDir: "~/data/launcher"